#lwr:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 10  

  # Position Controllers ---------------------------------------
  joint0_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_arm_0_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_arm_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_arm_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_arm_3_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_arm_4_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_arm_5_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_arm_6_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  # Separate Trajectory Controllers ---------------------------------------
  lwr_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints: 
      - lwr_arm_0_joint
      - lwr_arm_1_joint
      - lwr_arm_2_joint
      - lwr_arm_3_joint
      - lwr_arm_4_joint
      - lwr_arm_5_joint
      - lwr_arm_6_joint
    gains:
      lwr_arm_0_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
      lwr_arm_1_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
      lwr_arm_2_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
      lwr_arm_3_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
      lwr_arm_4_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
      lwr_arm_5_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
      lwr_arm_6_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}

  #   Joint Impedance Controllers
  JointImpedanceControl:
  type: kuka_controllers/JointImpedanceController
  root_name: lwr_arm_0_joint
  tip_name: lwr_arm_6_joint
  stiffness_gains: 30
  damping_gains: .7