lwr:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------
  joint0_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_0_joint
    pid: {p: 21000.0, i: 10.0, d: 0.0}
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_1_joint
    pid: {p: 50000.0, i: 10.0, d: 0.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_2_joint
    pid: {p: 50000.0, i: 10.0, d: 0.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_3_joint
    pid: {p: 50000.0, i: 10.0, d: 0.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_4_joint
    pid: {p: 50000.0, i: 10.0, d: 0.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_5_joint
    pid: {p: 50000.0, i: 10.0, d: 0.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: lwr_6_joint
    pid: {p: 50000.0, i: 10.0, d: 0.0}

  # Trajectory Controllers ---------------------------------------
  joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints: 
      - lwr_0_joint
      - lwr_1_joint
      - lwr_2_joint
      - lwr_3_joint
      - lwr_4_joint
      - lwr_5_joint
      - lwr_6_joint
    gains:
      lwr_0_joint: {p: 550,  d: 20, i: 10, i_clamp: 30} # {p: 25,  d: 5, i: 5, i_clamp: 30}
      lwr_1_joint: {p: 200,  d: 10, i: 5, i_clamp: 30}
      lwr_2_joint: {p: 50,  d: 5, i: 10, i_clamp: 30}
      lwr_3_joint: {p: 25,  d: 5, i: 5, i_clamp: 30}
      lwr_4_joint: {p: 15,  d: 5, i: 5, i_clamp: 10}
      lwr_5_joint: {p: 10,  d: 5, i: 5, i_clamp: 10}
      lwr_6_joint: {p: 10,  d: 5, i: 5, i_clamp: 10}

    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  25            # Override default
    action_monitor_rate: 30            # Override default
    stop_trajectory_duration: 0        # Override default
