# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  right_arm_a1_joint:
    has_velocity_limits: true
    max_velocity: 0.191986217719
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_a2_joint:
    has_velocity_limits: true
    max_velocity: 0.191986217719
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_e1_joint:
    has_velocity_limits: true
    max_velocity: 0.223402144255
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_a3_joint:
    has_velocity_limits: true
    max_velocity: 0.223402144255
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_a4_joint:
    has_velocity_limits: true
    max_velocity: 0.356047167407
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_a5_joint:
    has_velocity_limits: true
    max_velocity: 0.321140582367
    has_acceleration_limits: false
    max_acceleration: 0
  right_arm_a6_joint:
    has_velocity_limits: true
    max_velocity: 0.321140582367
    has_acceleration_limits: false
    max_acceleration: 0