# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  lwr_0_joint:
    has_velocity_limits: true
    max_velocity: 0.24
    has_acceleration_limits: true
    max_acceleration: 0.5
  lwr_1_joint:
    has_velocity_limits: true
    max_velocity: 0.24
    has_acceleration_limits: true
    max_acceleration: 0.5
  lwr_2_joint:
    has_velocity_limits: true
    max_velocity: 0.24
    has_acceleration_limits: true
    max_acceleration: 0.8
  lwr_3_joint:
    has_velocity_limits: true
    max_velocity: 0.24
    has_acceleration_limits: true
    max_acceleration: 0.8
  lwr_4_joint:
    has_velocity_limits: true
    max_velocity: 0.24
    has_acceleration_limits: true
    max_acceleration: 0.8
  lwr_5_joint:
    has_velocity_limits: true
    max_velocity: 0.24
    has_acceleration_limits: true
    max_acceleration: 0.8
  lwr_6_joint:
    has_velocity_limits: true
    max_velocity: 0.24
    has_acceleration_limits: true
    max_acceleration: 0.8